package com.xdev.rcdemo.loadData.ui.views;

import com.vaadin.navigator.ViewChangeListener;
import com.xdev.rcdemo.loadData.entities.Category;
import com.xdev.rcdemo.loadData.entities.Category_;
import com.xdev.rcdemo.loadData.ui.generators.CategoryPictureColumn;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.table.XdevTable;

public class ShowInTable extends XdevView {

	/**
	 *
	 */
	public ShowInTable() {
		super();
		this.initUI();
	}

	@Override
	public void enter(ViewChangeListener.ViewChangeEvent event) {
		super.enter(event);
	
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.table = new XdevTable<>();

		this.table.setContainerDataSource(Category.class);
		this.table.addGeneratedColumn("picture", new CategoryPictureColumn.Generator());
		this.table.setVisibleColumns(Category_.categoryid.getName(), Category_.categoryname.getName(),
				Category_.description.getName(), Category_.picture.getName());

		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(1);
		this.table.setSizeFull();
		this.gridLayout.addComponent(this.table, 0, 0);
		this.gridLayout.setColumnExpandRatio(0, 100.0F);
		this.gridLayout.setRowExpandRatio(0, 100.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private XdevTable<Category> table;
	private XdevGridLayout gridLayout;
	// </generated-code>

}
