
package com.xdev.rcdemo.loadData.ui;

import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevVerticalLayout;
import com.xdev.ui.XdevView;
import com.xdev.ui.navigation.Navigation;

public class MainView extends XdevView {

	/**
	 *
	 */
	public MainView() {
		super();
		this.initUI();
	}

	@Override
	public void enter(final ViewChangeListener.ViewChangeEvent event) {
		super.enter(event);

	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #buttonEmployeeForm}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void buttonEmployeeForm_buttonClick(final Button.ClickEvent event) {
		Navigation.to("employeeForm").navigate();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #buttonEmployeeTable}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void buttonEmployeeTable_buttonClick(final Button.ClickEvent event) {
		Navigation.to("employeesInTable").navigate();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #buttonCategoryTable}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void buttonCategoryTable_buttonClick(final Button.ClickEvent event) {
		Navigation.to("categoryTable").navigate();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #buttonGetPDF}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void buttonGetPDF_buttonClick(final Button.ClickEvent event) {
		Navigation.to("showPDF").navigate();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.verticalLayout = new XdevVerticalLayout();
		this.label = new XdevLabel();
		this.buttonEmployeeForm = new XdevButton();
		this.label2 = new XdevLabel();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.buttonEmployeeTable = new XdevButton();
		this.buttonCategoryTable = new XdevButton();
		this.label3 = new XdevLabel();
		this.buttonGetPDF = new XdevButton();

		this.label.setValue("Get image content from a entity and show it besides a form");
		this.buttonEmployeeForm.setCaption("Employees");
		this.label2.setValue("Show image from a entity in a table with a column generator");
		this.horizontalLayout.setMargin(new MarginInfo(false));
		this.buttonEmployeeTable.setCaption("Employees");
		this.buttonCategoryTable.setCaption("Categories");
		this.label3.setValue("Get a file - e.g. a PDF -  from a entity and show it in a browser frame");
		this.buttonGetPDF.setCaption("PDF");

		this.buttonEmployeeTable.setSizeUndefined();
		this.horizontalLayout.addComponent(this.buttonEmployeeTable);
		this.horizontalLayout.setComponentAlignment(this.buttonEmployeeTable, Alignment.MIDDLE_CENTER);
		this.buttonCategoryTable.setSizeUndefined();
		this.horizontalLayout.addComponent(this.buttonCategoryTable);
		this.horizontalLayout.setComponentAlignment(this.buttonCategoryTable, Alignment.MIDDLE_CENTER);
		this.label.setSizeUndefined();
		this.verticalLayout.addComponent(this.label);
		this.verticalLayout.setComponentAlignment(this.label, Alignment.MIDDLE_CENTER);
		this.buttonEmployeeForm.setSizeUndefined();
		this.verticalLayout.addComponent(this.buttonEmployeeForm);
		this.verticalLayout.setComponentAlignment(this.buttonEmployeeForm, Alignment.MIDDLE_CENTER);
		this.label2.setSizeUndefined();
		this.verticalLayout.addComponent(this.label2);
		this.verticalLayout.setComponentAlignment(this.label2, Alignment.MIDDLE_CENTER);
		this.horizontalLayout.setSizeUndefined();
		this.verticalLayout.addComponent(this.horizontalLayout);
		this.verticalLayout.setComponentAlignment(this.horizontalLayout, Alignment.MIDDLE_CENTER);
		this.label3.setSizeUndefined();
		this.verticalLayout.addComponent(this.label3);
		this.verticalLayout.setComponentAlignment(this.label3, Alignment.MIDDLE_CENTER);
		this.buttonGetPDF.setSizeUndefined();
		this.verticalLayout.addComponent(this.buttonGetPDF);
		this.verticalLayout.setComponentAlignment(this.buttonGetPDF, Alignment.MIDDLE_CENTER);
		final CustomComponent verticalLayout_spacer = new CustomComponent();
		verticalLayout_spacer.setSizeFull();
		this.verticalLayout.addComponent(verticalLayout_spacer);
		this.verticalLayout.setExpandRatio(verticalLayout_spacer, 1.0F);
		this.verticalLayout.setSizeFull();
		this.setContent(this.verticalLayout);
		this.setSizeFull();

		this.buttonEmployeeForm.addClickListener(event -> this.buttonEmployeeForm_buttonClick(event));
		this.buttonEmployeeTable.addClickListener(event -> this.buttonEmployeeTable_buttonClick(event));
		this.buttonCategoryTable.addClickListener(event -> this.buttonCategoryTable_buttonClick(event));
		this.buttonGetPDF.addClickListener(event -> this.buttonGetPDF_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel label, label2, label3;
	private XdevButton buttonEmployeeForm, buttonEmployeeTable, buttonCategoryTable, buttonGetPDF;
	private XdevHorizontalLayout horizontalLayout;
	private XdevVerticalLayout verticalLayout;
	// </generated-code>

}
